src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 * @UniqueEntity(fields={"username"}, message="There is already an account with this username")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank(message="Vous devez saisir une adresse email.")
     * @Assert\Email(message="Le format de l'adresse n'est pas correcte.")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=25, unique=true)
     * @Assert\NotBlank(message="Vous devez saisir un nom d'utilisateur.")
     */
    private $username;

    /**
     * @ORM\OneToMany(targetEntity=Task::class, mappedBy="user", cascade="remove")
     */
    private $tasks;

    public function __construct()
    {
        $this->tasks = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->username;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string)$this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function addRole(string $role): self
    {
        if (!in_array($role, $this->roles)) {
            $this->roles[] = $role;
        }

        return $this;
    }

    public function removeRole(string $role): self
    {
        $key = array_search($role, $this->roles);
        if ($key !== false) {
            unset($this->roles[$key]);
        }
        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string)$this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @return Collection|Task[]
     */
    public function getTasks(): Collection
    {
        return $this->tasks;
    }

    public function addTask(Task $task): self
    {
        if (!$this->tasks->contains($task)) {
            $this->tasks[] = $task;
            $task->setUser($this);
        }

        return $this;
    }

    public function removeTask(Task $task): self
    {
        if ($this->tasks->removeElement($task)) {
            // set the owning side to null (unless already changed)
            if ($task->getUser() === $this) {
                $task->setUser(null);
            }
        }

        return $this;
    }

    public function getDisplayRole(): array
    {
        if (in_array('ROLE_ADMIN', $this->getRoles())) {
            return [
                'name' => 'Administrateur',
                'color' => 'danger'
            ];
        };
        return [
            'name' => 'Utilisateur',
            'color' => 'success'
        ];
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken;
use Symfony\Component\Security\Core\Authorization\AccessDecisionManagerInterface;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Validator\Constraints\IsTrue;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class UserType extends AbstractType
{
    /**
     * @var Security
     */
    private $security;
    /**
     * @var AccessDecisionManagerInterface
     */
    private $decisionManager;
    /**
     * @var User
     */
    private $user;

    /**
     * UserType constructor.
     * @param Security $security
     * @param AccessDecisionManagerInterface $decisionManager
     */
    public function __construct(Security $security, AccessDecisionManagerInterface $decisionManager)
    {
        $this->security = $security;
        $this->decisionManager = $decisionManager;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // Check if user to modify is Admin
        $this->user = ($options['data']);

        $builder
            ->add('username', null, [
                'label' => 'Nom d\'utilisateur'
            ])
            ->add('email')
            ->add('plainPassword', RepeatedType::class, $this->getPasswordFieldOptions());

        if ($this->security->isGranted("ROLE_ADMIN")) {
            $this->addAdminCheckbox($builder);
        }
        if ($this->security->isGranted('IS_ANONYMOUS')) {
            $this->addAgreeTermsCheckbox($builder);
        }
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }

    private function getPasswordFieldOptions()
    {
        return [
            'label' => 'Mot de passe',
            'type' => PasswordType::class,
            'invalid_message' => 'Les deux mots de passe doivent correspondre.',
            'first_options' => ['label' => 'Mot de passe'],
            'second_options' => ['label' => 'Tapez le mot de passe à nouveau'],
            // instead of being set onto the object directly,
            // this is read and encoded in the controller
            'mapped' => false,
            'constraints' => [
                new NotBlank([
                    'message' => 'Entrez un mot de passe',
                ]),
                new Length([
                    'min' => 6,
                    'minMessage' => 'Votre mot de passe doit faire au moins {{ limit }} caractères',
                    // max length allowed by Symfony for security reasons
                    'max' => 4096,
                ]),
            ],
        ];
    }

    private function addAdminCheckbox(FormBuilderInterface $builder)
    {
        $builder->add('admin', CheckboxType::class, [
            'mapped' => false,
            'label' => 'Administrateur',
            'required' => false,
            'data' => $this->isAdmin(),
            'attr' => [
                'class' => 'switch'
            ],
        ]);
    }

    private function addAgreeTermsCheckbox(FormBuilderInterface $builder)
    {
        $builder->add('agreeTerms', CheckboxType::class, [
            'label' => 'J\'accepte les conditions d\'utilisation',
            'mapped' => false,
            'constraints' => [
                new IsTrue([
                    'message' => 'Vous devez accepter les conditions d\'utilisation',
                ]),
            ],
        ]);
    }

    private function isAdmin()
    {
        $token = new UsernamePasswordToken($this->user, 'none', 'none', $this->user->getRoles());
        return $this->decisionManager->decide($token, ['ROLE_ADMIN']);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Handler\Forms\UserFormHandler;
use App\Handler\PaginatorHandler;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

class UserController extends AbstractController
{
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;
    /**
     * @var PasswordEncoderInterface
     */
    private $passwordEncoder;
    /**
     * @var PaginatorHandler
     */
    private $pager;

    /**
     * UserController constructor.
     * @param EntityManagerInterface $entityManager
     * @param UserPasswordEncoderInterface $passwordEncoder
     * @param PaginatorHandler $pager
     */
    public function __construct(EntityManagerInterface $entityManager, UserPasswordEncoderInterface $passwordEncoder, PaginatorHandler $pager)
    {
        $this->entityManager = $entityManager;
        $this->passwordEncoder = $passwordEncoder;
        $this->pager = $pager;
    }

    /**
     * @Route("/admin/users", name="user_index")
     * @param UserRepository $userRepository
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function index(UserRepository $userRepository, Request $request)
    {
        $query = $userRepository->findAllQuery();
        return $this->render('user/index.html.twig', ['users' => $this->pager->paginate($request, $query)]);
    }

    /**
     * @Route("users/{id}/edit", name="user_edit")
     * @param User $user
     * @param Request $request
     * @param UserFormHandler $formHandler
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function edit(User $user, Request $request, UserFormHandler $formHandler)
    {
        $this->denyAccessUnlessGranted('USER_EDIT', $user);

        if ($formHandler->handle($request, $user,UserType::class)) {
            $this->addFlash('success', "L'utilisateur a bien été modifié");
            if ($this->isGranted('ROLE_ADMIN')) {
                return $this->redirectToRoute('user_index');
            }
            return $this->redirectToRoute('homepage');
        }

        return $this->render('user/edit.html.twig', ['form' => $formHandler->createView(), 'user' => $user]);
    }

    /**
     * @Route("/users/{id}/delete", name="user_delete")
     * @param User $user
     * @param Request $request
     * @param SessionInterface $session
     * @param TokenStorageInterface $tokenStorage
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function delete(User $user, Request $request, SessionInterface $session, TokenStorageInterface $tokenStorage)
    {
        $this->denyAccessUnlessGranted('USER_DELETE', $user);
        if ($this->isCsrfTokenValid("delete" . $user->getId(), $request->get("_token"))) {
            if ($this->getUser()->getId() === $user->getId()) {
                $this->container->get('security.token_storage')->setToken(null);
                $this->entityManager->remove($user);
                $this->entityManager->flush();
                $this->addFlash('success', 'Votre compte a bien été supprimée.');
                return $this->redirectToRoute('app_login');
            }

            $this->entityManager->remove($user);
            $this->entityManager->flush();

            $this->addFlash('success', 'L\'utilisateur a bien été supprimée.');
            return $this->redirectToRoute('user_index');
        }
        $this->addFlash('error', 'Token invalide');
        return $this->redirectToRoute('user_index');
    }
}

templates/user/_delete_form.html.twig
<form id="delete_form_user_{{ user.id }}"
		method="post" class="d-inline-block"
	  action="{{ path("user_delete", {id: user.id}) }}"
	  onsubmit="return confirm('Êtes vous sur de vouloir supprimer cet utilisateur?')">
	<input type="hidden" name="_method" value="DELETE"> <input type="hidden" name="_token"
															   value="{{ csrf_token("delete" ~ user.id) }}">
	<button type="submit" href="#" class="btn btn-sm btn-danger">
		<span class="fa fa-trash"></span>
	</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
	{{ form_row(form.username) }}
	{{ form_row(form.email) }}
	{{ form_row(form.plainPassword, {
		label: 'Mot de passe'
	}) }}
{% if form.admin is defined %}
	{{ form_row(form.admin) }}
{% endif %}
{% if form.agreeTerms is defined %}
	{{ form_row(form.agreeTerms) }}
{% endif %}

<button type="submit" class="btn btn-primary">Valider</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier l'utilisateur{% endblock %}

{% block body %}
	{% for flashError in app.flashes('verify_email_error') %}
		<div class="alert alert-danger" role="alert">{{ flashError }}</div>
	{% endfor %}
	
	<h1 class="h3 my-2 font-weight-normal">Modifier l'utilisateur :</h1>
	
	{{ form_start(form) }}
	{{ form_row(form.username) }}
	{{ form_row(form.email) }}
	{{ form_row(form.plainPassword, {
		label: 'Mot de passe'
	}) }}
	{{ form_row(form.agreeTerms) }}
	
	<button type="submit" class="btn btn-primary">Valider</button>
	{{ form_end(form) }}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block header_img %}{% endblock %}

{% block header_title %}<h1 class=py-3>Liste des utilisateurs</h1>{% endblock %}

{% block body %}
	
	<div class="py-3">
		<a href="{{ path('user_new') }}" class="btn btn-primary">Créer un utilisateur</a>
	</div>
	
	{% if users|length == 0 %}
		<div class="alert alert-warning" role="alert">
			Il n'y a pas encore d'utilisateur enregistré.
			<a href="{{ path('app_register') }}" class="btn btn-warning float-right">Créer un utilisateur</a>
		</div>
	{% else %}
		<div class="row">
			<div class="col-12">
				<table class="table responsive">
					<thead>
					<tr>
						<th>Nom d'utilisateur</th>
						<th>Adresse d'utilisateur</th>
						<th>Role</th>
						<th>Actions</th>
					</tr>
					</thead>
					<tbody>
					{% for user in users %}
						<tr>
							<td>{{ user.username }}</td>
							<td>{{ user.email }}</td>
							<td><span class="text-{{ user.displayRole.color }}">{{ user.displayRole.name }}</span></td>
							<td>
								<a href="{{ path('admin_task_index', {'user' : user.id}) }}" class="btn btn-success btn-sm">
									<span class="fa fa-tasks"></span>
								</a>
								<a href="{{ path('user_edit', {'id' : user.id}) }}" class="btn btn-warning btn-sm">
									<span class="fa fa-edit"></span>
								</a>
								{% include 'user/_delete_form.html.twig' %}
							</td>
						</tr>
					{% endfor %}
					</tbody>
				</table>
			</div>
			<div class="col-12">
				{{ knp_pagination_render(users) }}
			</div>
		</div>
	{% endif %}
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier l'utilisateur{% endblock %}

{% block body %}
	{% for flashError in app.flashes('verify_email_error') %}
		<div class="alert alert-danger" role="alert">{{ flashError }}</div>
	{% endfor %}
	
	<h1 class="h3 my-2 font-weight-normal">Ajouter un utilisateur :</h1>
	
	{% include 'user/_form.html.twig' %}
{% endblock %}